version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Dokan
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  build-test-lint:
    jobs:
      - build-and-test
